In [2]:
import pandas as pd
from sklearn.impute import SimpleImputer
import numpy as np
import pickle
from imblearn.over_sampling import SMOTE

### Pred

In [3]:
df = pd.read_csv(r'E:\iNeuron\APSFailureDetection\prediction_file_from_DB\aps_test_set.csv')
df

Idx  class  aa_000  ab_000        ac_000  ad_000  ae_000  af_000  \
0          0     -1      60     0.0  2.000000e+01    12.0     0.0     0.0   
1          1     -1      82     0.0  6.800000e+01    40.0     0.0     0.0   
2          2     -1   66002     2.0  2.120000e+02   112.0     0.0     0.0   
3          3     -1   59816     NaN  1.010000e+03   936.0     0.0     0.0   
4          4     -1    1814     NaN  1.560000e+02   140.0     0.0     0.0   
...      ...    ...     ...     ...           ...     ...     ...     ...   
15995  15995     -1   81852     NaN  2.130706e+09   892.0     0.0     0.0   
15996  15996     -1      18     0.0  5.200000e+01    46.0     8.0    26.0   
15997  15997     -1   79636     NaN  1.670000e+03  1518.0     0.0     0.0   
15998  15998     -1     110     NaN  3.600000e+01    32.0     0.0     0.0   
15999  15999     -1       8     0.0  6.000000e+00     4.0     2.0     2.0   

       ag_000  ag_001  ...    ee_002    ee_003    ee_004    ee_005     ee_006  \
0         0.0     0.0  ...    1098.0     138.0     412.0     654.0       78.0   
1         0.0     0.0  ...    1068.0     276.0    1620.0     116.0       86.0   
2         0.0     0.0  ...  495076.0  380368.0  440134.0  269556.0  1315022.0   
3         0.0     0.0  ...  540820.0  243270.0  483302.0  485332.0   431376.0   
4         0.0     0.0  ...    7646.0    4144.0   18466.0   49782.0     3176.0   
...       ...     ...  ...       ...       ...       ...       ...        ...   
15995     0.0     0.0  ...  632658.0  273242.0  510354.0  373918.0   349840.0   
15996     0.0     0.0  ...     266.0      44.0      46.0      14.0        2.0   
15997     0.0     0.0  ...  806832.0  449962.0  778826.0  581558.0   375498.0   
15998     0.0     0.0  ...     588.0     210.0     180.0     544.0     1004.0   
15999     0.0     0.0  ...      46.0      10.0      48.0      14.0       42.0   

         ee_007    ee_008   ee_009  ef_000  eg_000  
0          88.0       0.0      0.0     0.0     0.0  
1         462.0       0.0      0.0     0.0     0.0  
2      153680.0     516.0      0.0     0.0     0.0  
3      210074.0  281662.0   3232.0     0.0     0.0  
4         482.0      76.0      0.0     0.0     0.0  
...         ...       ...      ...     ...     ...  
15995  317840.0  960024.0  25566.0     0.0     0.0  
15996       0.0       0.0      0.0     0.0     0.0  
15997  222866.0  358934.0  19548.0     0.0     0.0  
15998    1338.0      74.0      0.0     0.0     0.0  
15999      46.0       0.0      0.0     0.0     0.0  

[16000 rows x 172 columns]

In [4]:
df.replace('na', np.nan, inplace=True)

In [5]:
test_X,test_y = df.drop(columns = ['class']), df['class']

In [6]:
for _ in test_X.columns:
    test_X[_] = test_X[_].astype('float64')

In [7]:
imp = SimpleImputer(strategy = 'median')
test_X = pd.DataFrame(imp.fit_transform(test_X), columns=test_X.columns)
test_X

Idx   aa_000  ab_000        ac_000  ad_000  ae_000  af_000  ag_000  \
0          0.0     60.0     0.0  2.000000e+01    12.0     0.0     0.0     0.0   
1          1.0     82.0     0.0  6.800000e+01    40.0     0.0     0.0     0.0   
2          2.0  66002.0     2.0  2.120000e+02   112.0     0.0     0.0     0.0   
3          3.0  59816.0     0.0  1.010000e+03   936.0     0.0     0.0     0.0   
4          4.0   1814.0     0.0  1.560000e+02   140.0     0.0     0.0     0.0   
...        ...      ...     ...           ...     ...     ...     ...     ...   
15995  15995.0  81852.0     0.0  2.130706e+09   892.0     0.0     0.0     0.0   
15996  15996.0     18.0     0.0  5.200000e+01    46.0     8.0    26.0     0.0   
15997  15997.0  79636.0     0.0  1.670000e+03  1518.0     0.0     0.0     0.0   
15998  15998.0    110.0     0.0  3.600000e+01    32.0     0.0     0.0     0.0   
15999  15999.0      8.0     0.0  6.000000e+00     4.0     2.0     2.0     0.0   

       ag_001  ag_002  ...    ee_002    ee_003    ee_004    ee_005     ee_006  \
0         0.0     0.0  ...    1098.0     138.0     412.0     654.0       78.0   
1         0.0     0.0  ...    1068.0     276.0    1620.0     116.0       86.0   
2         0.0     0.0  ...  495076.0  380368.0  440134.0  269556.0  1315022.0   
3         0.0     0.0  ...  540820.0  243270.0  483302.0  485332.0   431376.0   
4         0.0     0.0  ...    7646.0    4144.0   18466.0   49782.0     3176.0   
...       ...     ...  ...       ...       ...       ...       ...        ...   
15995     0.0     0.0  ...  632658.0  273242.0  510354.0  373918.0   349840.0   
15996     0.0     0.0  ...     266.0      44.0      46.0      14.0        2.0   
15997     0.0     0.0  ...  806832.0  449962.0  778826.0  581558.0   375498.0   
15998     0.0     0.0  ...     588.0     210.0     180.0     544.0     1004.0   
15999     0.0     0.0  ...      46.0      10.0      48.0      14.0       42.0   

         ee_007    ee_008   ee_009  ef_000  eg_000  
0          88.0       0.0      0.0     0.0     0.0  
1         462.0       0.0      0.0     0.0     0.0  
2      153680.0     516.0      0.0     0.0     0.0  
3      210074.0  281662.0   3232.0     0.0     0.0  
4         482.0      76.0      0.0     0.0     0.0  
...         ...       ...      ...     ...     ...  
15995  317840.0  960024.0  25566.0     0.0     0.0  
15996       0.0       0.0      0.0     0.0     0.0  
15997  222866.0  358934.0  19548.0     0.0     0.0  
15998    1338.0      74.0      0.0     0.0     0.0  
15999      46.0       0.0      0.0     0.0     0.0  

[16000 rows x 171 columns]

In [8]:
test_X.drop(columns=['Idx'], inplace=True)

### Training Data

In [9]:
df_train = pd.read_csv(r'E:\iNeuron\APSFailureDetection\training_file_from_DB\aps_training_set.csv')
df_train

Idx  class  aa_000  ab_000        ac_000  ad_000  ae_000  af_000  \
0          0     -1   76698     NaN  2.130706e+09   280.0     0.0     0.0   
1          1     -1   33058     NaN  0.000000e+00     NaN     0.0     0.0   
2          2     -1   41040     NaN  2.280000e+02   100.0     0.0     0.0   
3          3     -1      12     0.0  7.000000e+01    66.0     0.0    10.0   
4          4     -1   60874     NaN  1.368000e+03   458.0     0.0     0.0   
...      ...    ...     ...     ...           ...     ...     ...     ...   
59995  59995     -1  153002     NaN  6.640000e+02   186.0     0.0     0.0   
59996  59996     -1    2286     NaN  2.130707e+09   224.0     0.0     0.0   
59997  59997     -1     112     0.0  2.130706e+09    18.0     0.0     0.0   
59998  59998     -1   80292     NaN  2.130706e+09   494.0     0.0     0.0   
59999  59999     -1   40222     NaN  6.980000e+02   628.0     0.0     0.0   

       ag_000  ag_001  ...     ee_002    ee_003     ee_004     ee_005  \
0         0.0     0.0  ...  1240520.0  493384.0   721044.0   469792.0   
1         0.0     0.0  ...   421400.0  178064.0   293306.0   245416.0   
2         0.0     0.0  ...   277378.0  159812.0   423992.0   409564.0   
3         0.0     0.0  ...      240.0      46.0       58.0       44.0   
4         0.0     0.0  ...   622012.0  229790.0   405298.0   347188.0   
...       ...     ...  ...        ...       ...        ...        ...   
59995     0.0     0.0  ...   998500.0  566884.0  1290398.0  1218244.0   
59996     0.0     0.0  ...    10578.0    6760.0    21126.0    68424.0   
59997     0.0     0.0  ...      792.0     386.0      452.0      144.0   
59998     0.0     0.0  ...   699352.0  222654.0   347378.0   225724.0   
59999     0.0     0.0  ...   440066.0  183200.0   344546.0   254068.0   

          ee_006    ee_007    ee_008    ee_009  ef_000  eg_000  
0       339156.0  157956.0   73224.0       0.0     0.0     0.0  
1       133654.0   81140.0   97576.0    1500.0     0.0     0.0  
2       320746.0  158022.0   95128.0     514.0     0.0     0.0  
3           10.0       0.0       0.0       0.0     4.0    32.0  
4       286954.0  311560.0  433954.0    1218.0     0.0     0.0  
...          ...       ...       ...       ...     ...     ...  
59995  1019768.0  717762.0  898642.0   28588.0     0.0     0.0  
59996      136.0       0.0       0.0       0.0     0.0     0.0  
59997      146.0    2622.0       0.0       0.0     0.0     0.0  
59998   194440.0  165070.0  802280.0  388422.0     0.0     0.0  
59999   225148.0  158304.0  170384.0     158.0     0.0     0.0  

[60000 rows x 172 columns]

In [10]:
smote = SMOTE()

In [11]:
df_train.replace('na', np.nan, inplace=True)

In [12]:
X,y = df_train.drop(columns = ['class']), df_train['class']

In [13]:
for _ in X.columns:
    X[_] = X[_].astype('float64')

In [14]:
imp = SimpleImputer(strategy = 'median')
X = pd.DataFrame(imp.fit_transform(X), columns=X.columns)
X

Idx    aa_000  ab_000        ac_000  ad_000  ae_000  af_000  \
0          0.0   76698.0     0.0  2.130706e+09   280.0     0.0     0.0   
1          1.0   33058.0     0.0  0.000000e+00   126.0     0.0     0.0   
2          2.0   41040.0     0.0  2.280000e+02   100.0     0.0     0.0   
3          3.0      12.0     0.0  7.000000e+01    66.0     0.0    10.0   
4          4.0   60874.0     0.0  1.368000e+03   458.0     0.0     0.0   
...        ...       ...     ...           ...     ...     ...     ...   
59995  59995.0  153002.0     0.0  6.640000e+02   186.0     0.0     0.0   
59996  59996.0    2286.0     0.0  2.130707e+09   224.0     0.0     0.0   
59997  59997.0     112.0     0.0  2.130706e+09    18.0     0.0     0.0   
59998  59998.0   80292.0     0.0  2.130706e+09   494.0     0.0     0.0   
59999  59999.0   40222.0     0.0  6.980000e+02   628.0     0.0     0.0   

       ag_000  ag_001  ag_002  ...     ee_002    ee_003     ee_004     ee_005  \
0         0.0     0.0     0.0  ...  1240520.0  493384.0   721044.0   469792.0   
1         0.0     0.0     0.0  ...   421400.0  178064.0   293306.0   245416.0   
2         0.0     0.0     0.0  ...   277378.0  159812.0   423992.0   409564.0   
3         0.0     0.0     0.0  ...      240.0      46.0       58.0       44.0   
4         0.0     0.0     0.0  ...   622012.0  229790.0   405298.0   347188.0   
...       ...     ...     ...  ...        ...       ...        ...        ...   
59995     0.0     0.0     0.0  ...   998500.0  566884.0  1290398.0  1218244.0   
59996     0.0     0.0     0.0  ...    10578.0    6760.0    21126.0    68424.0   
59997     0.0     0.0     0.0  ...      792.0     386.0      452.0      144.0   
59998     0.0     0.0     0.0  ...   699352.0  222654.0   347378.0   225724.0   
59999     0.0     0.0     0.0  ...   440066.0  183200.0   344546.0   254068.0   

          ee_006    ee_007    ee_008    ee_009  ef_000  eg_000  
0       339156.0  157956.0   73224.0       0.0     0.0     0.0  
1       133654.0   81140.0   97576.0    1500.0     0.0     0.0  
2       320746.0  158022.0   95128.0     514.0     0.0     0.0  
3           10.0       0.0       0.0       0.0     4.0    32.0  
4       286954.0  311560.0  433954.0    1218.0     0.0     0.0  
...          ...       ...       ...       ...     ...     ...  
59995  1019768.0  717762.0  898642.0   28588.0     0.0     0.0  
59996      136.0       0.0       0.0       0.0     0.0     0.0  
59997      146.0    2622.0       0.0       0.0     0.0     0.0  
59998   194440.0  165070.0  802280.0  388422.0     0.0     0.0  
59999   225148.0  158304.0  170384.0     158.0     0.0     0.0  

[60000 rows x 171 columns]

In [15]:
X.drop(columns=['Idx'], inplace=True)

In [16]:
X_,y_ = smote.fit_resample(X,y) 

In [18]:
y_.value_counts()

 1    59000
-1    59000
Name: class, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
train_X, test_X, train_y, test_y = train_test_split(X_,y_,test_size = 0.3, random_state = 50)

### Extra

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import plot_confusion_matrix

In [23]:
param_grid = {'n_estimators':800,
              'max_depth':13,
              'min_samples_split':12,
              'max_leaf_nodes':300,
              'ccp_alpha':0.01,
              'criterion': 'gini'}

rf = RandomForestClassifier(**param_grid)
rf.fit(train_X,train_y)

RandomForestClassifier(ccp_alpha=0.01, max_depth=13, max_leaf_nodes=300,
                       min_samples_split=12, n_estimators=800)

In [30]:
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

In [31]:
def convert(arr):
    ls = []
    for _ in arr:
        if _ == False:
            ls.append(1)
        else:
            ls.append(-1)
    return np.array(ls)

In [42]:
predicted_proba = rf.predict_proba(test_X)
y_predicted = (predicted_proba [:,1] >= 0.0196)
y_predicted = convert(y_predicted)
y_predicted

array([-1, -1, -1, ..., -1, -1, -1])

In [43]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_true=test_y, y_pred=y_predicted).ravel()

array([15625,     0,   375,     0], dtype=int64)

In [24]:
182*500+17471*10

265710

In [34]:
17631*500

8815500

In [44]:
pred_y = rf.predict(test_X)
pred_y

array([-1, -1, -1, ..., -1, -1, -1], dtype=int64)

In [45]:
confusion_matrix(y_true=test_y, y_pred=pred_y).ravel()

array([14628,   997,     8,   367], dtype=int64)

In [18]:
import xgboost as xgb

In [ ]:
grid = {'reg_lambda' : 1,
        'eta' : [0.05], 
        'subsample' : [0.6], 
        'colsample_bytree' : [1],
        'scale_pos_weight':[1/59]}

xgb_c = xgb.XGBClassifier(**grid)
xgb_c.fit(X_, y_)